# Generated by Django 2.2.7 on 2019-12-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191204_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcrete',
            name='category',
        ),
    ]
