# Generated by Django 2.2.7 on 2019-12-05 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogcrete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcrete',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogCategories'),
        ),
    ]
