# Generated by Django 2.2.7 on 2019-12-05 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191205_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcrete',
            name='category',
            field=models.ManyToManyField(to='blog.BlogCategories'),
        ),
        migrations.AlterField(
            model_name='blogcrete',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
